language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Fox"; coverage=true)'
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Fox"); Pkg.test("Fox"; coverage=true)'
